"""per-country display threshold

Revision ID: 4f7be991d350
Revises: ebd7a80407e5
Create Date: 2026-09-26 13:09:42.951973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f7be991d350'
down_revision: Union[str, Sequence[str], None] = 'ebd7a80407e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('min_display_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'min_display_score')
    # ### end Alembic commands ###
