"""submissions and labels

Revision ID: ebd7a80407e5
Revises: 3aa7821d3446
Create Date: 2026-09-26 12:32:12.700737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebd7a80407e5'
down_revision: Union[str, Sequence[str], None] = '3aa7821d3446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('is_iranian', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('labeled_by', sa.Text(), nullable=False),
    sa.Column('score_at_label', sa.Float(), nullable=False),
    sa.Column('labeled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('business_id')
    )
    op.create_table('submission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category_slug', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('contact_email', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('detected_score', sa.Float(), nullable=False),
    sa.Column('client_hash', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='status_valid'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_slug'], ['category.slug'], ),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_client_hash'), 'submission', ['client_hash'], unique=False)
    op.create_index('ix_submission_status_created', 'submission', ['status', 'created_at'], unique=False)
    op.add_column('report', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('report', sa.Column('review_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'review_note')
    op.drop_column('report', 'reviewed_at')
    op.drop_index('ix_submission_status_created', table_name='submission')
    op.drop_index(op.f('ix_submission_client_hash'), table_name='submission')
    op.drop_table('submission')
    op.drop_table('label')
    # ### end Alembic commands ###
