"""telegram checked at

Revision ID: 64470ede4aaf
Revises: 4f7be991d350
Create Date: 2026-09-26 13:18:25.903570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64470ede4aaf'
down_revision: Union[str, Sequence[str], None] = '4f7be991d350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('telegram_checked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'telegram_checked_at')
    # ### end Alembic commands ###
