"""initial schema

Revision ID: 3c5fd7097ca1
Revises: 
Create Date: 2026-09-25 16:42:12.972381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c5fd7097ca1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # No-ops when scripts/setup_db.sh already created them as superuser.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name_fa', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=False),
    sa.Column('parent_slug', sa.Text(), nullable=True),
    sa.Column('mvp', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source_mappings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['parent_slug'], ['category.slug'], ),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('country',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name_fa', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('do_not_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'value')
    )
    op.create_table('job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedupe_key', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'done', 'failed')", name='status_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_claim', 'job', ['status', 'run_after'], unique=False)
    op.create_index('uq_job_active_dedupe_key', 'job', ['dedupe_key'], unique=True, postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.create_table('source',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name_fa', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('account_required', sa.Boolean(), nullable=False),
    sa.Column('monthly_cap', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('name_fa', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=False),
    sa.Column('center', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('west', sa.Float(), nullable=False),
    sa.Column('south', sa.Float(), nullable=False),
    sa.Column('east', sa.Float(), nullable=False),
    sa.Column('north', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['country.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_geospatial_index('idx_city_center', 'city', ['center'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('quota_usage',
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('source_id', 'period')
    )
    op.create_geospatial_table('business',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name_fa', sa.Text(), nullable=True),
    sa.Column('name_latin', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('phone_e164', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_label', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('website_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("confidence_label IN ('high', 'medium', 'low')", name='confidence_label_valid'),
    sa.CheckConstraint("status IN ('active', 'hidden', 'removed_by_request', 'closed')", name='status_valid'),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_business_location', 'business', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_business_city_status', 'business', ['city_id', 'status'], unique=False)
    op.create_index('ix_business_name_latin_trgm', 'business', ['name_latin'], unique=False, postgresql_using='gin', postgresql_ops={'name_latin': 'gin_trgm_ops'})
    op.create_table('index_status',
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('per_source', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('city_id')
    )
    op.create_table('business_category',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('category_slug', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_slug'], ['category.slug'], ),
    sa.PrimaryKeyConstraint('business_id', 'category_slug')
    )
    op.create_index('ix_business_category_slug', 'business_category', ['category_slug', 'business_id'], unique=False)
    op.create_table('business_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.CheckConstraint("kind IN ('website', 'facebook', 'instagram', 'telegram', 'phone')", name='kind_valid'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'kind', 'value')
    )
    op.create_index('ix_business_link_kind_value', 'business_link', ['kind', 'value'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reason IN ('not_iranian', 'closed', 'wrong_info', 'remove_request')", name='reason_valid'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_business_id'), 'report', ['business_id'], unique=False)
    op.create_table('source_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id')
    )
    op.create_index(op.f('ix_source_record_business_id'), 'source_record', ['business_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('source_record_id', sa.UUID(), nullable=False),
    sa.Column('signal', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_record_id', 'signal')
    )
    op.create_index(op.f('ix_evidence_business_id'), 'evidence', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_business_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_source_record_business_id'), table_name='source_record')
    op.drop_table('source_record')
    op.drop_index(op.f('ix_report_business_id'), table_name='report')
    op.drop_table('report')
    op.drop_index('ix_business_link_kind_value', table_name='business_link')
    op.drop_table('business_link')
    op.drop_index('ix_business_category_slug', table_name='business_category')
    op.drop_table('business_category')
    op.drop_table('index_status')
    op.drop_index('ix_business_name_latin_trgm', table_name='business', postgresql_using='gin', postgresql_ops={'name_latin': 'gin_trgm_ops'})
    op.drop_index('ix_business_city_status', table_name='business')
    op.drop_geospatial_index('idx_business_location', table_name='business', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('business')
    op.drop_table('quota_usage')
    op.drop_geospatial_index('idx_city_center', table_name='city', postgresql_using='gist', column_name='center')
    op.drop_geospatial_table('city')
    op.drop_table('source')
    op.drop_index('uq_job_active_dedupe_key', table_name='job', postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.drop_index('ix_job_claim', table_name='job')
    op.drop_table('job')
    op.drop_table('do_not_index')
    op.drop_table('country')
    op.drop_table('category')
    # ### end Alembic commands ###
